# Custom Language File for Launcher Customizer

[ejs.app]
title = "Zgeg Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/pjrlazarus-ai/ZgegLauncher"
supportLink = "https://github.com/pjrlazarus-ai/ZgegLauncher/issues"

[ejs.welcome]
welcomeHeader = "WSH MA COUILLE BVN SUR SHTARMC"
welcomeDescription = "BAH VIENS SUR LE SERVER"
welcomeDescCTA = "ET LA TU CLIQUES ET PUIS TU TE CONNECTE MDR"
